# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='email',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
