# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketlist',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='bucketlist',
            name='date_modified',
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='condition',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='currency',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='keywords',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='max_price',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='min_price',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='sort_order',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
