# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='condition',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='currency',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='max_price',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='min_price',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='sort_order',
            field=models.TextField(blank=True),
        ),
    ]
